- README.md
Closes #9 
Improved the installation steps. Now the contributor can directly fork the repo using the link provided in the step itself (Either by clicking on Fork or the Fork icon).
Also added a code snippet for `clone` step.
> Improve install steps for fork and clone

- .gitpod.yml
- README.md
Closes #11 
Adds Gitpod to the project. It adds two separate links, one for those who wants to work on the client side and one for those who want to work on the server side.
> Add gitpod to the project

- README.md
closes issue #27
- made readme more understandable by giving more insights and adding a little more instructions
> docs: make readme more understandable

- client/package-lock.json
- client/package.json
- client/src/components/Login/Login.jsx
- client/src/index.css
- server/index.js
- implemented a new login system using mojoauth
- used id from mongodb instead of manually creating mine
> fix: login not working

- client/src/components/Login/Login.jsx
- server/.gitignore
- server/index.js
- server/package-lock.json
- server/package.json
- Hosted backend to heroku
- replaced all links with `localhost:4000` to the backend url
> merging into main

- README.md
- instruction on how to use .env
- instruction on how to use the local MongoDB database
> docs: how to use .env file

- client/src/App.js
* As discussed in #35 , the user gets a blank page on first ever visit or after clearing `localStorage` so the proposal is to fix this issue
> fix: Blank Page on first ever load (#35)

- README.md
- removed sawo
- add mojo auth in tech stack
> docs: add mojo for auth

- README.md
> docs: make mojo name short

- client/.env_sample
- client/src/Context.jsx
- client/src/components/Login/Login.jsx
Closes #57 
Changes the prefix of env variables from `REACT_APP` to `VITE` to solve the bug caused by #54
> bug: changes env variables prefix to VITE

- client/src/components/NavBar/NavBar.jsx
- Fix confusing arrow function
> fix(NavBar.jsx): Confusing arrow function

- server/index.js
- server/models/UserSchema.js
- server/users.js
> Commets added 

- client/.env_sample
- client/src/Context.jsx
- client/src/components/Chat/Chat.jsx
- client/src/components/SearchUser/OnClickOnStart/OnClickOnStart.jsx
- server/.env_sample
- server/index.js
- server/users.js
> Roomconnect

- client/.env_sample
- client/src/components/Chat/Chat.jsx
- server/index.js
- changed the event to receive messages and send messages for their respective purposes
> feat: seeing messages

- .github/workflows/build.yml
- Changed the `npm install` in `build.yaml` to `npm ci` to speed up the installation of dependencies
> updated npm install to npm ci to install latest dependencies

- README.md
- closes #78 
- updated Discord link form 'https://discord.gg/KUWjx4fygJ' to 'https://discord.gg/ufcysW9q23'
> Updating Discord link

- client/package-lock.json
- client/package.json
- client/src/components/Chat.jsx
- client/src/context/Context.jsx
- client/src/pages/Searching.jsx
- server/index.js
- server/users.js
Closes #83 
* Users can now resume their chats after re-connections (i.e route changes, browser refresh, network problems, etc)
* Improved socket context initialization
* Added loading animations to improve UX on the search page
> Feat: random pairing v2

- README.md
Fix 'View Demo' link in README.md linking to wrong location.
`Closes #92`
Previously: https://github.com/Dun-sin/Whisper/issues/new?assignees=&labels=bug&template=bug_report.md&title=
Now: https://whischat.vercel.app/
> docs: correct link in README

- README.md
Closes #98 
- Remove Redux file from Readme File
- Kindly check the Readme File.
> fix: Remove redux from Readme file

- client/src/pages/ComingSoon.jsx
- client/src/pages/Start.jsx
Closes #75
- Changed the font size of some texts for better responsiveness.
> fix: solve responsiveness issue

- client/src/components/Chat.jsx
Closes #101
- removed type casting of `userID` to number
> fix: remove wrong type casting

- client/src/components/NavBar.jsx
- client/src/components/Routes.jsx
- client/src/pages/Logout.jsx
Closes #47
* Created a Logout file reusing AuthContext logic
* Created a logout function 
* Implement a button in the Navbar
> feat: Implement logout button

- client/src/components/Anonymous.jsx
- client/src/context/ChatContext.jsx
- client/src/index.jsx
- client/src/styles/chat.css
Closes #68
Created a Close chat function redirect to search chats
Implement a button in the Navbar Menu
> feat: modification is made for close chat button

- client/src/pages/Start.jsx
fixes #111 
Mitigated the underline and color change effect in start button [ Start.jsx ]
- [ x My code follows the code style of this project.
NA - Cursor is hidden while taking ss
> fix: hover effects on Start button removed 

- client/src/context/reducers/authReducer.js
Closes #109 
Alert in `src/context/reducers/authReducer.js` file removed
> fix: logout alert removed

- client/src/pages/Login.jsx
Removed the sign-in text from sign-in page
> Removed the sign-in text from sign-in page

- client/src/pages/Searching.jsx
-added new background color
- [ x] My code follows the code style of this project.
- [ x] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.
> feat: changed background color 

- client/src/context/Context.jsx
- client/src/pages/Searching.jsx
Example: Closes #115 
* Fixed delay in random user pairing on initial load (#115)
* Increased searching timeout to 15 seconds for random pairing
> fix: random pairing

- client/src/pages/Login.jsx
- removed the background
- added underline on hover
> feat: change login anonymously UI

- client/src/lib/axios.js
- client/src/pages/Login.jsx
- package-lock.json
- package.json
- server/index.js
Closes #140 
* Improved user registration flow
* Created a re-usable axios util to avoid code duplication
* Used validator package for user email validation
> feat: improvement on user registration flow

- client/src/components/Chat.jsx
- client/src/context/ChatContext.jsx
- client/src/context/reducers/chatReducer.js
- client/src/styles/chat.css
- package-lock.json
- package.json
- server/index.js
Closes #137 
* Positioned messages based on the sender
* Added uuid library for generating unique ids
> feat: positioned messages based on sender

- client/src/pages/Login.jsx
- server/index.js
Closes #145 
* Updated reference to undefined 'validator' object in `server/index.js`
* Fixed memory leak in Login.jsx (updating state after component unmounted)
This is a hotfix following my last pr #142.
I observed there were some bugs so I fixed them.
> fix: reference error + memory leak

- client/.eslintrc.json
- client/src/components/Anonymous.jsx
- client/src/components/BuddyMatcher.jsx
- client/src/components/Chat.jsx
- client/src/components/MessageStatus.jsx
- client/src/context/ChatContext.jsx
- client/src/context/reducers/chatReducer.js
- client/src/lib/chat.js
- client/src/pages/Searching.jsx
- client/src/styles/chat.css
- server/index.js
- server/users.js
Closes #134 
* moved sendMessage logic into a separate file
* implemented message feedback from server
* added message sent status
* This pr contains a lot of refactorings, but they're necessary to get this feature working
* I also modified the eslintrc.json file to disable some global errors I was getting
> feat: added message sent status

- client/src/components/Chat.jsx
- client/src/components/MessageStatus.jsx
- server/index.js
Closes #135 
Closes #126
* added resend message option
> feat: added resend message option

- client/src/components/Chat.jsx
- client/src/context/ChatContext.jsx
- client/src/context/reducers/chatReducer.js
- client/src/lib/chat.js
- client/src/styles/chat.css
- server/index.js
Closes #136 
* Added delete message feature
> feat: added delete message feature

- client/src/components/BuddyMatcher.jsx
- client/src/components/NavBar.jsx
- client/src/context/ChatContext.jsx
- client/src/context/reducers/authReducer.js
- client/src/context/reducers/chatReducer.js
- server/index.js
- server/users.js
Closes #154 
* clear user's data completely on logout
* automatically close chats for anonymous users on logout
> fix: clear user's data completely on logout

- client/src/components/Anonymous.jsx
- client/src/components/BuddyMatcher.jsx
- client/src/context/ChatContext.jsx
- client/src/context/reducers/chatReducer.js
- server/index.js
Closes #127 
* Clicking on `close chat` removes every info
> feat: clicking on 'close chat' removes every info

- client/src/components/Chat.jsx
Closes #155 
* Enhanced chatting on multiple devices
> feat: enhanced chatting on multiple devices

- client/src/context/reducers/chatReducer.js
> fix: close all chats not working

- client/src/context/reducers/chatReducer.js
> fix: close all chats not working (#161)

- client/src/components/Chat.jsx
- client/src/context/reducers/chatReducer.js
- client/src/lib/chat.js
- server/index.js
- fix edit message not being received by the other user
> fix: edit message not received

- server/index.js
- server/lib.js
- server/models/ActiveUserModel.js
> fix: backend bug

- README.md
> fix: updated the logo in Readme

- client/src/components/Anonymous.jsx
- client/src/components/BuddyMatcher.jsx
**My PR closes #185 **
* added close and re-search button
> feat: added close and re-search button

- client/src/components/NavBar.jsx
- server/index.js
**My PR closes #187 **
* Remove users from waiting list on logout
> fix: remove users from waiting list on logout

- client/src/components/BuddyMatcher.jsx
**My PR closes #217**
* Clicking on the stop button updates the context with latest changes
> fix: update context when stop btn is clicked

- client/src/styles/chat.css
- client/tailwind.config.js
**My PR closes #234 **
I added a "highlight" variable and used it to change color of the chat bubbles
> feat: Add highlight color

- client/src/styles/chat.css
- client/tailwind.config.js
**My PR closes #235**
Change background color for input and output messages.
> feat: change chat color (#235)

- client/src/components/Anonymous.jsx
- client/src/hooks/useKeyPress.ts
**My PR closes #186**
Added next shortcuts:
ctrl/cmd + n: close chat and start looking for a new partner
ctrl/cmd + c: close chat
> feat: added shortcuts keys

- client/src/components/NavBar.jsx
- package-lock.json
- package.json
**My PR closes #242 
I have changed icon pack from `react-icons` to `iconify` .
> feat: icon pack changed from react-icons to iconify #242

- client/src/components/Chat.jsx
- client/src/styles/chat.css
**My PR closes #221**
- add copy to clipboard option
- change alignment of text
> feat(chat.jsx): add option to copy to clipboard

- README.md
Issue No : #250 
Updated the Docker Link that Redirects to Docker rather than MongoDB
**My PR closes #issue_number_here**
> Updated the Docker Link

- client/src/pages/Profile.jsx
**My PR closes #260*
Added a save changes button
> feat: added a save changes btn #260

- client/src/components/Chat.jsx
- client/src/styles/chat.css
**My PR closes #257**
- Added markdown support using markdown-it library
> feat: add markdown support in chat section

- README.md
- add kinde to tools
- keep one Gitpod link
> add: kinde for auth

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/doc_issue.yml
- .github/ISSUE_TEMPLATE/features.yml
- .github/ISSUE_TEMPLATE/other.yml
- add hacktober fest label to all issue templates
> chore: add hacktoberfest label

- client/src/components/Chat.jsx
- client/src/lib/badWords.js
**My PR closes #281**
- render the markdown when displaying message and not while sending
- export bad words into its own file
> fix: editing returning an html element

- README.md
**My PR closes #295**
Fixed wrong npm command in  README.md
> docs: fixed wrong command

- client/src/styles/chat.css
- change background for quote Reply
- [] Solve the Blockquoto background, for the receiver & sender.
- [] Made both components with different colors.
- For Receiver:
- For Sender:
> feat: add background to blockquote

- client/src/context/reducers/authReducer.js
- client/src/pages/Profile.jsx
- got the variable for email properly
> fix: undefined email in profile

- .github/ISSUE_TEMPLATE/config.yml
closes #298
--> Removed the discord url
--> Added new discord url
Made the required changes.
Before
After
> fix: 298-Invalid discord link

- client/src/pages/Profile.jsx
Fixes Issue
closes #317
- added a text indication so user can know when their profile has been updated.
- text color green
> feat: give an indication when profile is updated

- client/src/components/Chat.jsx
- client/src/lib/browserNotification.js
- client/src/pages/Start.jsx
My PR closes #306 
Added a browser notification for when a new message is received. 
Request BrowserNotifcation permissions on main dashboard (after logging in)
Only send the browser notifications if user has given permission
> feat: send notification for new message

- .gitignore
**My PR closes #issue_number_here**
- removed gitignore file
> fix: deleted gitignore file

- client/package-lock.json
- client/package.json
**My PR closes #304 **
- Installed "prop-types" devDependency successfully 
- please check if the solution meets requirements, if not please ping me again I will be happy to solve as per the requirements if not matched
> fix: added prop-types as dev dependencies

- client/src/components/BuddyMatcher.jsx
- added `!app.currentChatId` for conditionally rendering loader component
https://github.com/Dun-sin/Whisper/assets/48488310/54b076c1-732b-4dfc-83fb-8eecdfb4def9
> fix: search screen showing chat ui for a brief moment

- server/sockets/logout.js
**My PR closes #303**
- Added missing dependencies to server sockets logout module
- Linked issue might have to be updated - since the suspected cause differed than the actual
https://github.com/Dun-sin/Whisper/assets/42728874/136ea74b-c75a-4864-b15c-ff3b0c5d14ce
> fix: add missing dependencies to server sockets logout

- README.md
> docs: Alignment of codeblocks with same level of indent in README

- client/src/App.jsx
- client/src/components/Anonymous.jsx
- client/src/components/BuddyMatcher.jsx
- client/src/components/Chat.jsx
- client/src/components/Dialog.jsx
- client/src/components/MessageStatus.jsx
- client/src/context/DarkModeContext.jsx
- client/src/index.jsx
- client/src/pages/ComingSoon.jsx
- client/src/pages/Login.jsx
- client/src/pages/Profile.jsx
- client/src/pages/Settings.jsx
- client/src/pages/Start.jsx
- client/src/styles/chat.css
- client/src/styles/dialog.css
- client/tailwind.config.js
> feat: add light/dark mode

- client/src/pages/Settings.jsx
**My PR closes #401**
Adding inline CSS to the three Form.HelpText component.
> fix: changing Settings.jsx frontend text color to white

- client/src/components/Chat.jsx
**My PR closes #417**
Changed the state of a message to an empty string after the message is sent.
> fix: message not clearing after form submission in Chat component

- client/src/pages/Settings.jsx
> fix: default mode for toggle

- client/src/components/Anonymous.jsx
**My PR closes #462 **
added shortcut for searching a new partner.
> fix: added shortcut  for searching a new partner

- client/src/pages/Start.jsx
Closes #472 
The start button now changes colour upon hovering.
After change:
https://github.com/Dun-sin/Whisper/assets/69362333/bcb0276c-459f-41c6-91f1-15f72d63849a
> fix: Fixes issue #472, Changes colour upon hover to the Start button

- client/src/components/Chat.jsx
- client/src/context/ChatContext.jsx
- client/src/context/reducers/chatReducer.js
- client/src/lib/chat.js
- server/models/MessageModel.js
- server/sockets/editMessage.js
- server/utils/lib.js
**My PR closes #183 **
- add icon to indicate
- add history of old messages
> feat: indication of message being edited

- client/src/components/Dialog.jsx
**My PR closes #469**
Changed the visibility of the cancel button.
> fix: logout cancel button is invisible

- client/src/App.jsx
- client/src/pages/NoPage.jsx
closes #486 
Add Custom 404 Page
> feat: Add Custom 404 Page

- client/src/pages/Profile.jsx
**My PR closes #412 **
Corrected Tailwind CSS classes for the "Save Changes" button color.
**on hover:**
> fix: update classes for Save Changes Button

- client/src/components/NavBar.jsx
**My PR closes #issue_number_here**
- add min-h-[55px] in className for navbar
- add h-full in linkStyle
> feat: navbar should have a height on mobile

- client/src/components/EmojiPicker.jsx
My PR Fixes #517
Enable searching for emojis in emoji picker
> feat: Enable searching for emojis in emoji picker

- .github/ISSUE_TEMPLATE/bug.yml
**My PR closes #515 ** 
- Added bug issue template
> chore: Added bug issue template

- client/src/lib/browserNotification.js
My PR Fixes #527 
Block bad words from showing in notification
> feat: block bad words from showing in notification

- client/src/App.jsx
- client/src/components/Anonymous.jsx
- client/src/context/AppContext.jsx
- client/src/context/reducers/appReducer.js
- constants.json
- server/index.js
- server/sockets/onlineStatus.js
**My PR closes #532 **
- add online status, for when the user was last online
- update context and send it to the buddy
> feat: add online and last seen status

- client/src/components/NavBar.jsx
- client/src/pages/ComingSoon.jsx
**My PR closes #514 **
- fixed the navbar height on mobile
> fix: height on navbar

- server/.env_sample
**My PR closes #538 **
-> Added the text that was asked in the issue.
> docs: added the text given in issue in  env_sample file

- client/src/components/Anonymous.jsx
- client/src/components/Chat.jsx
- client/src/hooks/useCheckTimePassed.js
- client/src/hooks/useInactiveChat.jsx
- client/src/lib/browserNotification.js
- client/src/lib/chatHelper.js
**My PR closes #427 **
- create hook for checking how long has passed
- create a hook to send the right notification
> fix: inactivity notification

- client/src/pages/Login.jsx
**My PR closes #566 **
Changed "Login Anonlymously" text color to white
> fix: Changed "login anonymously" text color #566

- src/pages/settings.tsx
- src/styles/globals.css
My PR closes #589 
The volume slider in the settings had a width of 0 which made it unusable. Now it takes 100% of the available width which is better.
/
Before
After
> fix: Volume slider is unusable

- src/components/PageWrapper.tsx
- src/pages/anonymous.tsx
- src/pages/searching.tsx
**My PR closes #595**
* Chats are now properly restored no matter the page the user is currently on
> fix: properly restore chats

- client/src/context/AppContext.jsx
> fix: undefined settings for theme

- client/src/App.jsx
- client/src/components/Chat/DropDownOption.jsx
- client/src/hooks/useCryptoKeys.js
- client/src/lib/chatHelper.js
> Revert "fix: Copying chat not work"

- client/src/pages/Profile.jsx
**My PR closes #634 **
change minimum age to 12
> feat: change minimum age to 12

- CONTRIBUTING.md
**My PR closes [#649](https://github.com/Dun-sin/Whisper/issues/649)**
> docs: fixed anchor ref in contributing.md

- README.md
My PR fixes #648 
👨‍💻 Changes proposed(What did you do ?)
> docs: removed kinde from readme

- client/src/components/Chat.jsx
**My PR closes #631**
The replyTo ID is passed to the getRepliedMessage function. This ID is used to search within the decryptedMessages array, which already contains the decrypted messages. The function finds the message object that matches the replyTo, ID and returns it.everything is working fine.
- [1] My code follows the code style of this project.
- [2] This PR does not contain plagiarized content.
- [3] The title and description of the PR is clear and explains the approach.
> fix: Reply chat text not show

- client/src/components/NavBar.jsx
**My PR closes #644*
- I closed the dialog after logging out by by updating the state of setDialog in the logOut function.
> fix: close dialog after logging out

- client/src/components/Chat/MessageInput.jsx
My PR closes #668 
removed the fragment in messageInput since that component only has one fragment child we can remove the fragment and just return the form
> refactor: Remove the fragment in message Input 

- client/src/pages/Start.jsx
@Dun-sin 
**My PR closes #677 **
Added a button `Close Chat ` with `onClick` functionality to trigger a function call `doCloseChat()` which further emits a socket request from client side for event `NEW_EVENT_CLOSE` which further calls `emitClose()` function .
The `emitClose` function is responsible for handling the closure of a chat. If an error occurs while closing, it alerts the user; otherwise, it either closes the current chat or navigates the user back to the homepage, depending on whether the chat was successfully closed. The `clearTimer` function is called to stop any running timers. It further calls the `closeChat()` function.
The server listens to the request and broadcasts socket request from server side for event `NEW_EVENT_CLOSE`
which calls a function `onClose` to notify the …
> feat: Close chat functionality in home screen

- .github/ISSUE_TEMPLATE/bug.yml
**My PR closes #706**
Added "Steps to Reproduce" field to the GitHub issue template for bugs to prompt contributors to provide clear steps for reproducing bugs
> chore: Add 'Steps to Reproduce' field to issue template

- client/src/components/Chat.jsx
- client/src/components/Chat/BadwordWarning.jsx
- client/src/components/Chat/MessageList.jsx
- client/src/components/Chat/Status.jsx
**My PR closes #663 **
- created a component for status
- created a component for the bad word warning
-
> refactor: message list component

- .github/workflows/issue-assignment-labelling
after/before someone is assigned
**My PR closes #724 **
> docs: create GitHub action for automating labels

- client/package-lock.json
- client/package.json
- client/src/App.jsx
- client/src/context/reducers/authReducer.js
- client/src/lib/toast.js
My PR closes #768
I've added the toast message for auth pages so now when user logs in and logs out then user will get the toast message like: Login Successfully or Logout successfully. It works for both Anonymously login and Email Login.
https://github.com/user-attachments/assets/ea0f22d3-7e0a-40ec-9266-0c658de3364d
> feat: added toast message on login and logout
