Dun-sin/Whisper

client/src/components/Chat.jsx
**My PR closes #189**
Added a useEffect hook that adds an event listener for the `Escape` key and cancels editing.
=> feat: cancel editing on ESC key press

client/src/components/NavBar.jsx
**My PR closes #191  **
- Added a gap-3 to the nav bar items. Even if they are highlighted they still look separated now.
=> fix: added spacing to navbar icons

client/src/components/BuddyMatcher.jsx, server/index.js
closes #132 
Created a button titled as `Stop` in `BuddyMatcher.jsx` which is a link to `/` and redirects you to home on click. Since, there is an effect with the callback that closes the socket and does necessary steps when component unmounts. Therefore, I need not worry about the same when redirecting to `/` with react-router.
=> feat: added button to stop searching for a buddy

client/src/components/Anonymous.jsx, client/src/components/Chat.jsx
fixes #247
* Update the typing status accordingly (even if user loses connection)
=> fix: properly update typing status

client/src/components/Chat.jsx
**My PR closes #289
<h4> Removed the Delete Option for the receiver</h4> 
<h4>  Removed double menu on receiving message</h4>  
-  [X] My code follows the code style of this project.
<h2> View For Removed Double Menus </h2>
<h2>View For Removed Delete option for Receiver</h2>
=> fix: Resolve issue with double menu on receiving message

client/src/components/Chat.jsx
**My PR closes #320**
- The **warningMessage** function returns JSX element which markdownIt could not parse. So just added a check condition.
=> fix: Error in parsing messages containing bad words

client/src/components/Anonymous.jsx, client/src/hooks/useKeyPress.js
**Fixes #292**
- Implemented a Builder design pattern for better support shortcuts
- Changed shortcut for closing chat from "ctrl + c" to "ctrl + shift + x"
=> feat: added support for shift key in useKeyPress hook and changed mismatched shortcut

client/src/components/Chat.jsx
Trimmed the Input Message To Remove Extra Black Spaces
Before
After
=> fix: Blank Spaces In the Input Message

client/src/App.jsx, client/src/components/Chat.jsx
**My PR closes #288 **
added feature that can send message by [ctrl + enter] key.
=> feat: added send message by [ctrl+enter] key

client/index.html
**My PR closes #358**
- Updated `META` tags and website description.
- Added `Structured Data for Google Search` to improve SEO.
- Added icons link for `Shortcuts, Apple-Touch-Icon`.
- Added `Open Graph Meta Tags` to improve SEO.
=> feat: improved seo and meta tags

client/src/components/BuddyMatcher.jsx
added app.currentChatId dependency to the dependency array of useEffect(() => { on line 99 of Whisper/client/src/components/BuddyMatcher.jsx
My PR closes #388 
Added  app.currentChatId to the useEffect
=> fix: dependency array issue #388

client/src/pages/Profile.jsx
**My PR closes #410**
I have implemented client-side validation to **prevent users** from entering **negative values for age**. This was achieved by using HTML attributes and JavaScript validation.
Could you please consider adding the "hacktoberfest" and "hacktoberfest-accepted" labels to this pr? Thanks a bunch!
https://github.com/Dun-sin/Whisper/assets/110025628/7ce43ebb-90fa-4309-a17c-4b765a21b7ff
=> fix: Age Validation in Profile Section

client/src/pages/Settings.jsx
**My PR closes #450 **
I modified the code to ensure that warning message is displayed only when there are actual unsaved changes by checking 
`hasUnsavedSettings`. 
<details> <summary> Before Fix Evidence </summary>
https://github.com/Dun-sin/Whisper/assets/98248371/19f483f1-984c-49e4-a59d-a600c84cedd1
</details>
<details> <summary> After Fix Evidence </summary>
https://github.com/Dun-sin/Whisper/assets/98248371/65a961cd-21ec-4a47-8756-db21aca40c4c
</details>
<details> <summary>Code Changes</summary> 
</details>
=> fix: 'Unsaved Settings Warning' pops up for no reason #450

client/src/components/Chat.jsx
=> feat: add block option drop down

client/src/components/Anonymous.jsx, client/src/components/Chat/MessageInput.jsx
**My PR closes #419**
- while chatting displayed the appropriate placeholder
- Added display shortcuts in the dropdown
<br>
=> feat: Added display instructions for shortcuts

client/src/components/NavBar.jsx
**My PR closes #506 **
Separated settings and logout from the other navigations
=> fix: refactored Nav bar

README.md
Added a </a> closing tag after the img for SocketIo in README.md
**My PR closes Issue #500**
Add a  '\</a\>' closing tag after '\<img\>' for SocketIo in README.md
**Before:**
**After:**
=> docs: remove highlighting from text in README.md

.github/ISSUE_TEMPLATE/bug.yml, client/src/components/Chat.jsx, client/src/components/Chat/MessageInput.jsx, server/package-lock.json, server/package.json, server/sockets/sendMessage.js
**My PR closes #470**
Implemented Rate Limiter against Message Flooding.
When the user send 25 messages within a minute this will limit or block the messages - for message flooding and spamming
=> fix: Implemented Rate Limiter against Message Flooding.

client/package-lock.json, client/package.json, client/src/components/Chat.jsx, client/src/components/Chat/PreviousMessages.jsx, client/src/context/ChatContext.jsx, client/src/context/reducers/chatReducer.js, client/src/lib/browserNotification.js, client/src/lib/decryptMessage.js, server/package-lock.json, server/package.json, server/sockets/editMessage.js, server/utils/lib.js
**My PR closes #256 **
- fix sending and editing message so encryption can work properly
- use crypto js to encrypt and decrypt messages
=> feat: add encryption

client/src/components/Chat.jsx, client/src/components/Chat/MessageInput.jsx
**My PR closes #536 
- The fontsize of text inside the textarea was 18px + padding bottom(10px) + padding top(10px) it is 48 which is higher than its acutual height which is 45px so i increased it to 48px for the content to not overflow.
- I set overflow auto to both chat input and chat container which will only show scrollbar when the content overflows the container which solves the problem.
=> fix: scrollbar bug fixed

client/src/components/Chat/MessageSeen.jsx
**My PR closes #562 **
- Updated the condition for setting the 'seen' status. It now checks if the tab is active and if the user is not the sender.
=> fix: wrong seen message status

.env_sample
**My PR closes #578**
I added the `.env_sample` file to the root of the project so users can configure the `.env` file stipulated in the installation section of [README.md](https://github.com/Dun-sin/Whisper#%EF%B8%8F-installation).
=> fix: add .env_sample file

src/components/Chat.tsx, src/components/Chat/BadwordHideShow.tsx, src/types/propstypes.ts
**My PR closes #593**
I created a function called getBadwords, which imports BadWordsNext and EN only when handleSubmit is triggered. Additionally, I introduced a new component called BadwordHideShow, as it also utilizes badword and needed to be externalized.
This already enhances performance to some extent. However, I believe we can further modularize the chat section, enabling us to identify more performance optimization opportunities.
=> feat: Dynamic imports BadWordsNext Chat

package-lock.json, package.json, src/components/Chat.tsx, src/components/Chat/BadwordHideShow.tsx, src/components/Chat/DropDownOption.tsx, src/components/Chat/MessageSeen.tsx, src/components/NavBar.tsx, src/components/PageWrapper.tsx, src/context/AppContext.tsx, src/context/ChatContext.tsx, src/lib/chatHelper.ts, src/lib/chatSocket.ts, src/lib/decryptMessage.ts, src/pages/anonymous.tsx, src/pages/index.tsx, src/pages/searching.tsx, src/reducer/appReducer.ts, src/reducer/chatReducer.ts, src/server/handlers.ts, src/server/lib/lib.ts, src/server/models/ActiveUserModel.ts, src/server/models/MessageModel.ts, src/types/contextTypes.ts, src/types/propstypes.ts, src/types/types.ts
**My PR closes #592 **
- changed naming to be consistent
=> refactor: consistent name for room

package-lock.json, package.json, src/components/Chat.tsx, src/lib/chatSocket.ts, src/server/service/mongo.ts, src/service/mailService.ts
**My PR closes #601 **
- add the `NEXT_PUBLIC_` for Next.js
- changes Next.js dev command to turn on debugging by default
- installed cross-env for debugging
=> fix: add NEXT_PUBLIC_ to env

client/.prettierrc.json, client/src/App.jsx, client/src/components/Anonymous.jsx, client/src/components/Chat.jsx, client/src/components/Chat/DropDownOption.jsx, client/src/components/Chat/MessageInput.jsx, client/src/components/Chat/MessageSeen.jsx, client/src/components/Chat/PreviousMessages.jsx, client/src/components/Dialog.jsx, client/src/components/EmojiPicker.jsx, client/src/components/NavBar.jsx, client/src/components/UserAvatar.jsx, client/src/context/AppContext.jsx, client/src/context/ChatContext.jsx, client/src/context/reducers/chatReducer.js, client/src/hooks/useInactiveChat.jsx, client/src/index.jsx, client/src/lib/browserNotification.js, client/src/lib/chatHelper.js, client/src/lib/decryptMessage.js, client/src/pages/ComingSoon.jsx, client/src/pages/Profile.jsx, client/src/pages/Settings.jsx, client/src/pages/SignupAnonUser.jsx, documentation.md, server/package.json, server/sockets/join.js, server/sockets/requestPublicKey.js
**My PR closes #610 **
- add setTimeout for key generation to occur so it gets to all users
- ran linter
=> fix: message not sending

client/src/components/Chat/DropDownOption.jsx, client/src/lib/chatHelper.js
**My PR closes #628 **
- used the `useCryptoKeys` hook to get the `importedPrivateKey` and `cryptoKey`
- passd the needed keys to `handleCopyToClipboard` function
- decrypted the message using the `decryptMessage` function and the key
=> fix: use the decryptMessage function to get the original text

client/src/pages/Login.jsx
- set error when code inputted is wrong
- move error message p tag to the bottom of the forms
=> feat: add error message

client/package-lock.json, client/package.json, client/src/components/Chat.jsx, client/src/components/Loading.jsx, client/src/hooks/useCryptoKeys.js
**My PR closes #630**
- install and use react-spinner for loading animation
- import messageIsDecrypting from useCryptokeys in chat
- export messageIsDecrypting from useCryptoKeys
- create loading component
- 
=> feat: add a loader to show when decrypting messgaes

client/src/components/NavBar.jsx
**My PR closes #670**
Removed propTypes from NavBar.jsx.
The following two pieces of code have been removed:
```js
import PropTypes from 'prop-types';
```
and
```js
NavBar.propTypes = { 
className: PropTypes.string, 
}; 
```
Removed import for proptypes.
=> chore: remove nav proptype (#670)

client/src/components/Chat/MessageSeen.jsx
My PR closes #678 
Added Tailwind to the <p> tag that holds the seen or not seen message text.
I added `dark:text-white text-primary`
=> fix: seen message text in light mode

client/src/components/Anonymous.jsx, client/src/components/MenuToggle.jsx
**My PR closes #660 **
Moved menu toggle into it's own component `MenuToggle.jsx`.
Added the screen Recording of menu toggle working.
Screen Recordings
[Screencast from 29-08-24 10:48:52 AM IST.webm](https://github.com/user-attachments/assets/25043c56-b7bd-43be-b3e4-962bf38abc12)
[Screencast from 29-08-24 10:48:14 AM IST.webm](https://github.com/user-attachments/assets/c3ae7edb-e83f-4f77-9872-519cd818dbf6)
=> refactor: Moved menu toggle into it's own component.

client/src/App.jsx, client/src/components/Anonymous.jsx, client/src/components/BuddyMatcher.jsx, client/src/hooks/useCloseChat.jsx, client/src/lib/socketConnection.js, client/src/pages/Start.jsx, constants.json, server/sockets/close.js
**My PR closes #698 **
- Wrap start.jsx with the ChatProvider
- make the connectWithId a promise function so we await connectivity with socket and make sure it's done before any operation
- create the close chat button
- Change event name for after chat has been closed from `new_event_close` to `new_event_closed`
=> feat: create a hook for closing chat

client/src/components/Chat.jsx, client/src/lib/chatSocket.js
**My PR closes #664**
- Moved all socket-related logic (both `emit` and `on` methods) from the `Chat` component to the `useChatUtils` hook.
- Created a `setupSocketListeners` function in `useChatUtils` to handle all socket event listeners (`NEW_EVENT_RECEIVE_MESSAGE`, `NEW_EVENT_DELETE_MESSAGE`, etc.) and cleanup.
- Updated the `Chat` component to use the refactored methods from `useChatUtils`.
https://github.com/user-attachments/assets/ce4bbf0b-f63c-4a83-842b-2bfb47b09a6a
https://github.com/user-attachments/assets/d409ac3d-e39b-4e1a-a901-cabc6340023b
=> refactor: move socket emit/on methods to useChatUtils hook

server/utils/lib.js
My PR closes #708
Removed CryptoJS import module
Removed CryptoJS encrypt from editMessage functionality
- [✔️] My code follows the code style of this project.
- [✔️] This PR does not contain plagiarized content.
- [✔️] The title and description of the PR is clear and explains the approach.
=> fix: delete unneeded line of code from lib.js in server folder

client/src/components/BuddyMatcher.jsx, client/src/components/ReconnectBanner.jsx
**closes #662**
- Created a new component ReconnectBanner at client/src/components/
- Integrated it into BuddyMatcher.jsx
- Refactored unnecessary code from BuddyMatcher.jsx
- The changes made will not affect the UI or functionality.
NA
=> refactor: Created ReconnectBanner component and modify BuddyMatcher

client/src/components/Chat/DropDownOption.jsx
**My PR closes #704**
- Removed the unnecessary call to `updateMessage` to prevent crashing when deleting a message.
- Updated the function to only call `updateMessage` when needed.
https://github.com/user-attachments/assets/bb3729cb-6a99-4818-bacf-bfded97c0c16
=> fix: crash when deleting a message

client/src/components/Chat/DropDownOption.jsx, constants.json, server/sockets/deleteMessage.js, server/sockets/editMessage.js, server/utils/lib.js
**My PR closes #705**
- Added a restriction to prevent users from editing or deleting messages after 15 minutes to promote message integrity.
- Implemented frontend checks to hide edit/delete options if the message is older than 15 minutes.
- Added backend validation to prevent edit/delete requests from bypassing the 15-minute restriction.
https://github.com/user-attachments/assets/7163cb53-cf27-47f0-bab8-2fb2a59e5fbb
=> feat:  add 15-minute restriction on message edit/delete options

client/src/components/Chat/MessageList.jsx
=> refactor: change condition to use the logical AND operator

client/src/components/Chat/BadwordWarning.jsx
**My PR closes #666 **
Did few changes:
1. Replaced span with button.
2. Added some styling to button and on hover button.
3. Added a gap between the text and button.
Normal : <br>
<br>
On hover: <br>
=> style: change the span to button for badword element #666

client/src/components/Chat/MessageList.jsx, server/sockets/editMessage.js
**My PR closes #722 **
- this happened because the function that checks if a message can be edited or deleted wasn't imported
- added a try catch around the editmessage socket
=> fix: editing a message not working

client/src/lib/browserNotification.js, client/src/pages/Start.jsx
**My PR closes #730 **
Changed the response of notification trigger function . Added a dialog if the user denies the permission . 
I would suggest to first show the dialog and then request for permission .
=> feat: add a dialog if User denies notfication permission

client/src/components/NavBar.jsx
**My PR closes #739**
Fixed tab alignment issue by setting the height to 100%.
**Before**
**After**
=> fix: add height 100% to resolve tab alignment issue

CONTRIBUTING.md
**My PR closes #653**
- Added a section in the CONTRIBUTING.md file explaining how to create a branch using `git checkout`.
- Included instructions on how to push the newly created branch.
- Replaced the existing link with the new section link in the CONTRIBUTING.md file.
=> docs:  Add instructions for creating and pushing a branch to CONTRIBUTING.md

server/package-lock.json, server/package.json
**My PR closes #751**
Removing unused package `image-moderation` in the server application that is unreleased
=> fix: removing unused package image-moderation in server

client/src/pages/Home.jsx
**My PR closes #747**
The issue of unwanted scrollbars appearing due to image overflow was fixed by applying Tailwind CSS classes ( max-h-[90vh] )to the  tag and removed 'h-auto' class because it was not required. The change will cause image to resize according to the available space and will not overflow due to different aspect ratio of screen.
Before
After
=> fix : resolved the image overflow through adding tailwind css class

client/src/pages/Profile.jsx
**My PR closes #760 **
- Added `min="12"` and `max="120"` to age input field.
I have added minimum age as 12 and the maximum as 120 as it was not mentioned what will be the upper bound
=> fix: restrict invalid values in age input field

client/src/components/BuddyMatcher.jsx, client/src/lib/buddySocket.js
**My PR closes #661**
I moved all socket functions from
https://github.com/Dun-sin/Whisper/blob/dbec99c68f63c606647ea2cef1d458a72ae83b1b/client/src/components/BuddyMatcher.jsx and moved them into a file in lib folder called buddySocket.js.
=> refactor(socket): move all socket functions to lib/buddySocket.js
